### ISSUE TITLE
Jupyter-server 2.0 support

### ISSUE THREAD

**Issue by kliegr** [run-ai/jupyterlab_genv#16]
Are you planning to support the current version of the Jupyter server?
The installation returns
`jupyterlab-genv 0.3.0 requires jupyter-server<2,>=1.6, but you have jupyter-server 2.12.5 which is incompatible.`

Thanks

**Comment by rotenbergrr** [comment]
hi @kliegr and thanks for reaching out!

for sure I want to support this version of Jupyter server.
I don't think there will be any issues with supporting it.

I will try to find some time to do this

**Comment by rotenbergrr** [comment]
hi @kliegr ,
I released version 0.4.0 with support for `jupyter-server` versions 2.x.
pls lmk if something does not work.

thanks again for reaching out!
